apiVersion: v1
kind: ConfigMap
metadata:
  name: e-book-service
  namespace: scholarpath
  labels: { app.kubernetes.io/name: e-book-service, scholarpath.io/domain: library }
data:
  LOG_LEVEL: info
  PORT: "50221"
