apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-repository
  namespace: scholarpath
  labels: { app.kubernetes.io/name: resource-repository, scholarpath.io/domain: library }
data:
  LOG_LEVEL: info
  PORT: "50222"
