apiVersion: v1
kind: Service
metadata:
  name: resource-repository
  namespace: scholarpath
  labels: { app.kubernetes.io/name: resource-repository, scholarpath.io/domain: library }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50222, targetPort: 50222 }]
  selector: { app.kubernetes.io/name: resource-repository }
