apiVersion: v1
kind: Service
metadata:
  name: submission-service
  namespace: scholarpath
  labels: { app.kubernetes.io/name: submission-service, scholarpath.io/domain: lms }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50101, targetPort: 50101 }]
  selector: { app.kubernetes.io/name: submission-service }
