cloud:
  provider: gcp
  storageClass: pd-balanced
  ingressClass: gce

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: scholarpath-feature-flag-proxy@{{ .Values.gcp.project }}.iam.gserviceaccount.com
