config:
  rootDomain: pomerium.scholarpath.internal
  generateSignedJWT: true
authenticate:
  idp:
    provider: oidc
    url: https://keycloak.scholarpath.internal
ingressController: { enabled: true }
