scholarpath:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres.scholarpath.svc
      user: dbt
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      dbname: scholarpath_warehouse
      schema: public
      threads: 8
    prod:
      type: trino
      host: trino.scholarpath.svc
      port: 8080
      catalog: iceberg
      schema: scholarpath_mart
      threads: 16
