apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-service
  namespace: scholarpath
  labels: { app.kubernetes.io/name: lms-service, scholarpath.io/domain: lms }
data:
  LOG_LEVEL: info
  PORT: "50500"
  KAFKA_BOOTSTRAP: "kafka.messaging:9092"
