apiVersion: v1
kind: Service
metadata:
  name: student-sso
  namespace: scholarpath
  labels: { app.kubernetes.io/name: student-sso, scholarpath.io/domain: identity }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50021, targetPort: 50021 }]
  selector: { app.kubernetes.io/name: student-sso }
