apiVersion: v1
kind: ConfigMap
metadata:
  name: virtual-classroom
  namespace: scholarpath
  labels: { app.kubernetes.io/name: virtual-classroom, scholarpath.io/domain: classroom }
data:
  LOG_LEVEL: info
  PORT: "50400"
  NATS_URL: "nats://nats.messaging:4222"
