apiVersion: v1
kind: Service
metadata:
  name: virtual-classroom
  namespace: scholarpath
  labels: { app.kubernetes.io/name: virtual-classroom, scholarpath.io/domain: classroom }
spec:
  type: ClusterIP
  ports:
    - { name: http, port: 50400, targetPort: 50400 }
    - { name: rtp,  port: 40000, targetPort: 40000, protocol: UDP }
  selector: { app.kubernetes.io/name: virtual-classroom }
